name: LeagueOfLegends
author: PogostickDev
main: me.pogostick01dev.leagueoflegends.Main
version: 1.0
description: A league of legends plugin.

commands:
    summonersrift:
        usage: /<command>
        description: Basic LeagueOfLegends command.